name: Java CI with JUnit Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Cloner le repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Java 17 (ou version de ton projet)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3. Construire le projet avec Maven
      - name: Build with Maven
        run: mvn -B clean install

      # 4. Exécuter les tests
      - name: Run tests
        run: mvn -B test

      # 5. Publier les résultats de test dans l'interface Github
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
